# Generated by Django 4.2.7 on 2024-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_respuestas_respuesta_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestas',
            name='respuesta_10',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestas',
            name='respuesta_11',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestas',
            name='respuesta_12',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestas',
            name='respuesta_13',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestas',
            name='respuesta_14',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestas',
            name='respuesta_15',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestas',
            name='respuesta_16',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestas',
            name='respuesta_17',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestas',
            name='respuesta_18',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
