# Generated by Django 4.2.7 on 2024-01-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_respuestas_respuesta_10_respuestas_respuesta_11_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuestasdos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_10', models.CharField(max_length=255)),
                ('respuesta_11', models.CharField(max_length=255)),
                ('respuesta_12', models.CharField(max_length=255)),
                ('respuesta_13', models.CharField(max_length=255)),
                ('respuesta_14', models.CharField(max_length=255)),
                ('respuesta_15', models.CharField(max_length=255)),
                ('respuesta_16', models.CharField(max_length=255)),
                ('respuesta_17', models.CharField(max_length=255)),
                ('respuesta_18', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='respuesta_10',
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='respuesta_11',
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='respuesta_12',
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='respuesta_13',
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='respuesta_14',
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='respuesta_15',
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='respuesta_16',
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='respuesta_17',
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='respuesta_18',
        ),
    ]
